version: '3.8'

services:
  mongo:
    image: mongo
    container_name: db-mongo-votes
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data:
