// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package com.sdg4.ms_statistics.proto;

public final class VoteProto {
  private VoteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocalDateTimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sdg4.votes.proto.compiledProto.LocalDateTime)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 year = 1;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    int getMonth();

    /**
     * <code>int32 day = 3;</code>
     * @return The day.
     */
    int getDay();

    /**
     * <code>int32 hour = 4;</code>
     * @return The hour.
     */
    int getHour();

    /**
     * <code>int32 minute = 5;</code>
     * @return The minute.
     */
    int getMinute();

    /**
     * <code>int32 second = 6;</code>
     * @return The second.
     */
    int getSecond();
  }
  /**
   * Protobuf type {@code com.sdg4.votes.proto.compiledProto.LocalDateTime}
   */
  public static final class LocalDateTime extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sdg4.votes.proto.compiledProto.LocalDateTime)
      LocalDateTimeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocalDateTime.newBuilder() to construct.
    private LocalDateTime(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocalDateTime() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocalDateTime();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocalDateTime(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              year_ = input.readInt32();
              break;
            }
            case 16: {

              month_ = input.readInt32();
              break;
            }
            case 24: {

              day_ = input.readInt32();
              break;
            }
            case 32: {

              hour_ = input.readInt32();
              break;
            }
            case 40: {

              minute_ = input.readInt32();
              break;
            }
            case 48: {

              second_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LocalDateTime.class, Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_;
    /**
     * <code>int32 year = 1;</code>
     * @return The year.
     */
    @Override
    public int getYear() {
      return year_;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    @Override
    public int getMonth() {
      return month_;
    }

    public static final int DAY_FIELD_NUMBER = 3;
    private int day_;
    /**
     * <code>int32 day = 3;</code>
     * @return The day.
     */
    @Override
    public int getDay() {
      return day_;
    }

    public static final int HOUR_FIELD_NUMBER = 4;
    private int hour_;
    /**
     * <code>int32 hour = 4;</code>
     * @return The hour.
     */
    @Override
    public int getHour() {
      return hour_;
    }

    public static final int MINUTE_FIELD_NUMBER = 5;
    private int minute_;
    /**
     * <code>int32 minute = 5;</code>
     * @return The minute.
     */
    @Override
    public int getMinute() {
      return minute_;
    }

    public static final int SECOND_FIELD_NUMBER = 6;
    private int second_;
    /**
     * <code>int32 second = 6;</code>
     * @return The second.
     */
    @Override
    public int getSecond() {
      return second_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (year_ != 0) {
        output.writeInt32(1, year_);
      }
      if (month_ != 0) {
        output.writeInt32(2, month_);
      }
      if (day_ != 0) {
        output.writeInt32(3, day_);
      }
      if (hour_ != 0) {
        output.writeInt32(4, hour_);
      }
      if (minute_ != 0) {
        output.writeInt32(5, minute_);
      }
      if (second_ != 0) {
        output.writeInt32(6, second_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, year_);
      }
      if (month_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, month_);
      }
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, day_);
      }
      if (hour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, hour_);
      }
      if (minute_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, minute_);
      }
      if (second_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, second_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LocalDateTime)) {
        return super.equals(obj);
      }
      LocalDateTime other = (LocalDateTime) obj;

      if (getYear()
          != other.getYear()) return false;
      if (getMonth()
          != other.getMonth()) return false;
      if (getDay()
          != other.getDay()) return false;
      if (getHour()
          != other.getHour()) return false;
      if (getMinute()
          != other.getMinute()) return false;
      if (getSecond()
          != other.getSecond()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (37 * hash) + HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getHour();
      hash = (37 * hash) + MINUTE_FIELD_NUMBER;
      hash = (53 * hash) + getMinute();
      hash = (37 * hash) + SECOND_FIELD_NUMBER;
      hash = (53 * hash) + getSecond();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LocalDateTime parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LocalDateTime parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LocalDateTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LocalDateTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LocalDateTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LocalDateTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LocalDateTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LocalDateTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LocalDateTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LocalDateTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LocalDateTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LocalDateTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LocalDateTime prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sdg4.votes.proto.compiledProto.LocalDateTime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sdg4.votes.proto.compiledProto.LocalDateTime)
        LocalDateTimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LocalDateTime.class, Builder.class);
      }

      // Construct using com.sdg4.votes.proto.VoteProto.LocalDateTime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        year_ = 0;

        month_ = 0;

        day_ = 0;

        hour_ = 0;

        minute_ = 0;

        second_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_descriptor;
      }

      @Override
      public LocalDateTime getDefaultInstanceForType() {
        return LocalDateTime.getDefaultInstance();
      }

      @Override
      public LocalDateTime build() {
        LocalDateTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LocalDateTime buildPartial() {
        LocalDateTime result = new LocalDateTime(this);
        result.year_ = year_;
        result.month_ = month_;
        result.day_ = day_;
        result.hour_ = hour_;
        result.minute_ = minute_;
        result.second_ = second_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LocalDateTime) {
          return mergeFrom((LocalDateTime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LocalDateTime other) {
        if (other == LocalDateTime.getDefaultInstance()) return this;
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (other.getMonth() != 0) {
          setMonth(other.getMonth());
        }
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        if (other.getHour() != 0) {
          setHour(other.getHour());
        }
        if (other.getMinute() != 0) {
          setMinute(other.getMinute());
        }
        if (other.getSecond() != 0) {
          setSecond(other.getSecond());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LocalDateTime parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LocalDateTime) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 1;</code>
       * @return The year.
       */
      @Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 1;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <code>int32 month = 2;</code>
       * @return The month.
       */
      @Override
      public int getMonth() {
        return month_;
      }
      /**
       * <code>int32 month = 2;</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(int value) {
        
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 month = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        
        month_ = 0;
        onChanged();
        return this;
      }

      private int day_ ;
      /**
       * <code>int32 day = 3;</code>
       * @return The day.
       */
      @Override
      public int getDay() {
        return day_;
      }
      /**
       * <code>int32 day = 3;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 day = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }

      private int hour_ ;
      /**
       * <code>int32 hour = 4;</code>
       * @return The hour.
       */
      @Override
      public int getHour() {
        return hour_;
      }
      /**
       * <code>int32 hour = 4;</code>
       * @param value The hour to set.
       * @return This builder for chaining.
       */
      public Builder setHour(int value) {
        
        hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hour = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHour() {
        
        hour_ = 0;
        onChanged();
        return this;
      }

      private int minute_ ;
      /**
       * <code>int32 minute = 5;</code>
       * @return The minute.
       */
      @Override
      public int getMinute() {
        return minute_;
      }
      /**
       * <code>int32 minute = 5;</code>
       * @param value The minute to set.
       * @return This builder for chaining.
       */
      public Builder setMinute(int value) {
        
        minute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 minute = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinute() {
        
        minute_ = 0;
        onChanged();
        return this;
      }

      private int second_ ;
      /**
       * <code>int32 second = 6;</code>
       * @return The second.
       */
      @Override
      public int getSecond() {
        return second_;
      }
      /**
       * <code>int32 second = 6;</code>
       * @param value The second to set.
       * @return This builder for chaining.
       */
      public Builder setSecond(int value) {
        
        second_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 second = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecond() {
        
        second_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sdg4.votes.proto.compiledProto.LocalDateTime)
    }

    // @@protoc_insertion_point(class_scope:com.sdg4.votes.proto.compiledProto.LocalDateTime)
    private static final LocalDateTime DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LocalDateTime();
    }

    public static LocalDateTime getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocalDateTime>
        PARSER = new com.google.protobuf.AbstractParser<LocalDateTime>() {
      @Override
      public LocalDateTime parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocalDateTime(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocalDateTime> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LocalDateTime> getParserForType() {
      return PARSER;
    }

    @Override
    public LocalDateTime getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sdg4.votes.proto.compiledProto.Vote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ID del voto
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <pre>
     * ID del voto
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * ID de la elección
     * </pre>
     *
     * <code>int32 electionId = 2;</code>
     * @return The electionId.
     */
    int getElectionId();

    /**
     * <pre>
     * ID de la boleta
     * </pre>
     *
     * <code>int32 ballotId = 3;</code>
     * @return The ballotId.
     */
    int getBallotId();

    /**
     * <pre>
     * ID del candidato
     * </pre>
     *
     * <code>int32 candidateId = 4;</code>
     * @return The candidateId.
     */
    int getCandidateId();

    /**
     * <pre>
     * Hora del voto
     * </pre>
     *
     * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
     * @return Whether the voteTime field is set.
     */
    boolean hasVoteTime();
    /**
     * <pre>
     * Hora del voto
     * </pre>
     *
     * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
     * @return The voteTime.
     */
    LocalDateTime getVoteTime();
    /**
     * <pre>
     * Hora del voto
     * </pre>
     *
     * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
     */
    LocalDateTimeOrBuilder getVoteTimeOrBuilder();
  }
  /**
   * Protobuf type {@code com.sdg4.votes.proto.compiledProto.Vote}
   */
  public static final class Vote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sdg4.votes.proto.compiledProto.Vote)
      VoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vote.newBuilder() to construct.
    private Vote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vote() {
      id_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Vote();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              electionId_ = input.readInt32();
              break;
            }
            case 24: {

              ballotId_ = input.readInt32();
              break;
            }
            case 32: {

              candidateId_ = input.readInt32();
              break;
            }
            case 42: {
              LocalDateTime.Builder subBuilder = null;
              if (voteTime_ != null) {
                subBuilder = voteTime_.toBuilder();
              }
              voteTime_ = input.readMessage(LocalDateTime.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(voteTime_);
                voteTime_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_Vote_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_Vote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Vote.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <pre>
     * ID del voto
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ID del voto
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELECTIONID_FIELD_NUMBER = 2;
    private int electionId_;
    /**
     * <pre>
     * ID de la elección
     * </pre>
     *
     * <code>int32 electionId = 2;</code>
     * @return The electionId.
     */
    @Override
    public int getElectionId() {
      return electionId_;
    }

    public static final int BALLOTID_FIELD_NUMBER = 3;
    private int ballotId_;
    /**
     * <pre>
     * ID de la boleta
     * </pre>
     *
     * <code>int32 ballotId = 3;</code>
     * @return The ballotId.
     */
    @Override
    public int getBallotId() {
      return ballotId_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 4;
    private int candidateId_;
    /**
     * <pre>
     * ID del candidato
     * </pre>
     *
     * <code>int32 candidateId = 4;</code>
     * @return The candidateId.
     */
    @Override
    public int getCandidateId() {
      return candidateId_;
    }

    public static final int VOTETIME_FIELD_NUMBER = 5;
    private LocalDateTime voteTime_;
    /**
     * <pre>
     * Hora del voto
     * </pre>
     *
     * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
     * @return Whether the voteTime field is set.
     */
    @Override
    public boolean hasVoteTime() {
      return voteTime_ != null;
    }
    /**
     * <pre>
     * Hora del voto
     * </pre>
     *
     * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
     * @return The voteTime.
     */
    @Override
    public LocalDateTime getVoteTime() {
      return voteTime_ == null ? LocalDateTime.getDefaultInstance() : voteTime_;
    }
    /**
     * <pre>
     * Hora del voto
     * </pre>
     *
     * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
     */
    @Override
    public LocalDateTimeOrBuilder getVoteTimeOrBuilder() {
      return getVoteTime();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (electionId_ != 0) {
        output.writeInt32(2, electionId_);
      }
      if (ballotId_ != 0) {
        output.writeInt32(3, ballotId_);
      }
      if (candidateId_ != 0) {
        output.writeInt32(4, candidateId_);
      }
      if (voteTime_ != null) {
        output.writeMessage(5, getVoteTime());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (electionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, electionId_);
      }
      if (ballotId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ballotId_);
      }
      if (candidateId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, candidateId_);
      }
      if (voteTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getVoteTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Vote)) {
        return super.equals(obj);
      }
      Vote other = (Vote) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getElectionId()
          != other.getElectionId()) return false;
      if (getBallotId()
          != other.getBallotId()) return false;
      if (getCandidateId()
          != other.getCandidateId()) return false;
      if (hasVoteTime() != other.hasVoteTime()) return false;
      if (hasVoteTime()) {
        if (!getVoteTime()
            .equals(other.getVoteTime())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + ELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getElectionId();
      hash = (37 * hash) + BALLOTID_FIELD_NUMBER;
      hash = (53 * hash) + getBallotId();
      hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateId();
      if (hasVoteTime()) {
        hash = (37 * hash) + VOTETIME_FIELD_NUMBER;
        hash = (53 * hash) + getVoteTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Vote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Vote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Vote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Vote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Vote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Vote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Vote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Vote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Vote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Vote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Vote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Vote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Vote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sdg4.votes.proto.compiledProto.Vote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sdg4.votes.proto.compiledProto.Vote)
        VoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_Vote_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_Vote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Vote.class, Builder.class);
      }

      // Construct using com.sdg4.votes.proto.VoteProto.Vote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        electionId_ = 0;

        ballotId_ = 0;

        candidateId_ = 0;

        if (voteTimeBuilder_ == null) {
          voteTime_ = null;
        } else {
          voteTime_ = null;
          voteTimeBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VoteProto.internal_static_com_sdg4_votes_proto_compiledProto_Vote_descriptor;
      }

      @Override
      public Vote getDefaultInstanceForType() {
        return Vote.getDefaultInstance();
      }

      @Override
      public Vote build() {
        Vote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Vote buildPartial() {
        Vote result = new Vote(this);
        result.id_ = id_;
        result.electionId_ = electionId_;
        result.ballotId_ = ballotId_;
        result.candidateId_ = candidateId_;
        if (voteTimeBuilder_ == null) {
          result.voteTime_ = voteTime_;
        } else {
          result.voteTime_ = voteTimeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Vote) {
          return mergeFrom((Vote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Vote other) {
        if (other == Vote.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getElectionId() != 0) {
          setElectionId(other.getElectionId());
        }
        if (other.getBallotId() != 0) {
          setBallotId(other.getBallotId());
        }
        if (other.getCandidateId() != 0) {
          setCandidateId(other.getCandidateId());
        }
        if (other.hasVoteTime()) {
          mergeVoteTime(other.getVoteTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Vote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Vote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <pre>
       * ID del voto
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * ID del voto
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ID del voto
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID del voto
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID del voto
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int electionId_ ;
      /**
       * <pre>
       * ID de la elección
       * </pre>
       *
       * <code>int32 electionId = 2;</code>
       * @return The electionId.
       */
      @Override
      public int getElectionId() {
        return electionId_;
      }
      /**
       * <pre>
       * ID de la elección
       * </pre>
       *
       * <code>int32 electionId = 2;</code>
       * @param value The electionId to set.
       * @return This builder for chaining.
       */
      public Builder setElectionId(int value) {
        
        electionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID de la elección
       * </pre>
       *
       * <code>int32 electionId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearElectionId() {
        
        electionId_ = 0;
        onChanged();
        return this;
      }

      private int ballotId_ ;
      /**
       * <pre>
       * ID de la boleta
       * </pre>
       *
       * <code>int32 ballotId = 3;</code>
       * @return The ballotId.
       */
      @Override
      public int getBallotId() {
        return ballotId_;
      }
      /**
       * <pre>
       * ID de la boleta
       * </pre>
       *
       * <code>int32 ballotId = 3;</code>
       * @param value The ballotId to set.
       * @return This builder for chaining.
       */
      public Builder setBallotId(int value) {
        
        ballotId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID de la boleta
       * </pre>
       *
       * <code>int32 ballotId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBallotId() {
        
        ballotId_ = 0;
        onChanged();
        return this;
      }

      private int candidateId_ ;
      /**
       * <pre>
       * ID del candidato
       * </pre>
       *
       * <code>int32 candidateId = 4;</code>
       * @return The candidateId.
       */
      @Override
      public int getCandidateId() {
        return candidateId_;
      }
      /**
       * <pre>
       * ID del candidato
       * </pre>
       *
       * <code>int32 candidateId = 4;</code>
       * @param value The candidateId to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateId(int value) {
        
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID del candidato
       * </pre>
       *
       * <code>int32 candidateId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCandidateId() {
        
        candidateId_ = 0;
        onChanged();
        return this;
      }

      private LocalDateTime voteTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          LocalDateTime, LocalDateTime.Builder, LocalDateTimeOrBuilder> voteTimeBuilder_;
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       * @return Whether the voteTime field is set.
       */
      public boolean hasVoteTime() {
        return voteTimeBuilder_ != null || voteTime_ != null;
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       * @return The voteTime.
       */
      public LocalDateTime getVoteTime() {
        if (voteTimeBuilder_ == null) {
          return voteTime_ == null ? LocalDateTime.getDefaultInstance() : voteTime_;
        } else {
          return voteTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       */
      public Builder setVoteTime(LocalDateTime value) {
        if (voteTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          voteTime_ = value;
          onChanged();
        } else {
          voteTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       */
      public Builder setVoteTime(
          LocalDateTime.Builder builderForValue) {
        if (voteTimeBuilder_ == null) {
          voteTime_ = builderForValue.build();
          onChanged();
        } else {
          voteTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       */
      public Builder mergeVoteTime(LocalDateTime value) {
        if (voteTimeBuilder_ == null) {
          if (voteTime_ != null) {
            voteTime_ =
              LocalDateTime.newBuilder(voteTime_).mergeFrom(value).buildPartial();
          } else {
            voteTime_ = value;
          }
          onChanged();
        } else {
          voteTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       */
      public Builder clearVoteTime() {
        if (voteTimeBuilder_ == null) {
          voteTime_ = null;
          onChanged();
        } else {
          voteTime_ = null;
          voteTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       */
      public LocalDateTime.Builder getVoteTimeBuilder() {
        
        onChanged();
        return getVoteTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       */
      public LocalDateTimeOrBuilder getVoteTimeOrBuilder() {
        if (voteTimeBuilder_ != null) {
          return voteTimeBuilder_.getMessageOrBuilder();
        } else {
          return voteTime_ == null ?
              LocalDateTime.getDefaultInstance() : voteTime_;
        }
      }
      /**
       * <pre>
       * Hora del voto
       * </pre>
       *
       * <code>.com.sdg4.votes.proto.compiledProto.LocalDateTime voteTime = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LocalDateTime, LocalDateTime.Builder, LocalDateTimeOrBuilder>
          getVoteTimeFieldBuilder() {
        if (voteTimeBuilder_ == null) {
          voteTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LocalDateTime, LocalDateTime.Builder, LocalDateTimeOrBuilder>(
                  getVoteTime(),
                  getParentForChildren(),
                  isClean());
          voteTime_ = null;
        }
        return voteTimeBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sdg4.votes.proto.compiledProto.Vote)
    }

    // @@protoc_insertion_point(class_scope:com.sdg4.votes.proto.compiledProto.Vote)
    private static final Vote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Vote();
    }

    public static Vote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vote>
        PARSER = new com.google.protobuf.AbstractParser<Vote>() {
      @Override
      public Vote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vote> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Vote> getParserForType() {
      return PARSER;
    }

    @Override
    public Vote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sdg4_votes_proto_compiledProto_Vote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sdg4_votes_proto_compiledProto_Vote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nvote.proto\022\"com.sdg4.votes.proto.compi" +
      "ledProto\"g\n\rLocalDateTime\022\014\n\004year\030\001 \001(\005\022" +
      "\r\n\005month\030\002 \001(\005\022\013\n\003day\030\003 \001(\005\022\014\n\004hour\030\004 \001(" +
      "\005\022\016\n\006minute\030\005 \001(\005\022\016\n\006second\030\006 \001(\005\"\222\001\n\004Vo" +
      "te\022\n\n\002id\030\001 \001(\t\022\022\n\nelectionId\030\002 \001(\005\022\020\n\010ba" +
      "llotId\030\003 \001(\005\022\023\n\013candidateId\030\004 \001(\005\022C\n\010vot" +
      "eTime\030\005 \001(\01321.com.sdg4.votes.proto.compi" +
      "ledProto.LocalDateTimeB!\n\024com.sdg4.votes" +
      ".protoB\tVoteProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sdg4_votes_proto_compiledProto_LocalDateTime_descriptor,
        new String[] { "Year", "Month", "Day", "Hour", "Minute", "Second", });
    internal_static_com_sdg4_votes_proto_compiledProto_Vote_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sdg4_votes_proto_compiledProto_Vote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sdg4_votes_proto_compiledProto_Vote_descriptor,
        new String[] { "Id", "ElectionId", "BallotId", "CandidateId", "VoteTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
